.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. veil_qt test_veil_qt
clean: FORCE
	$(MAKE) -C .. veil_qt_clean test_veil_qt_clean
check: FORCE
	$(MAKE) -C .. test_veil_qt_check
veil-qt veil-qt.exe: FORCE
	 $(MAKE) -C .. veil_qt
