#ifndef VEIL_WALLETINITFLAGS_H
#define VEIL_WALLETINITFLAGS_H

enum MnemonicWalletInitFlags
{
    SELECT_LANGUAGE,
    PROMPT_MNEMONIC,
    NEW_MNEMONIC,
    IMPORT_MNEMONIC,
    INVALID_MNEMONIC
};

#endif //VEIL_WALLETINITFLAGS_H
